import { useState } from "react";
import { Button, Card, Label, Textarea, Text } from "@/shared/components/ui";
import type { PromptVersionFormData } from "../type";
import { CAPABILITY_CONFIG } from "@/features/prompt-templates/utils/capability";
import { PURPOSE_CONFIG } from "@/features/prompt-templates/utils/purpose";

interface PromptVersionFormProps {
    initialSystemContext?: string;
    initialUserMessage?: string;
    initialCapability?: number;
    templatePurpose: number;
    onSubmit: (data: PromptVersionFormData) => void;
    onCancel: () => void;
    isSubmitting: boolean;
}

export function PromptVersionForm({
    initialSystemContext = "",
    initialUserMessage = "",
    initialCapability = 0,
    templatePurpose,
    onSubmit,
    onCancel,
    isSubmitting,
}: PromptVersionFormProps) {
    const [systemContext, setSystemContext] = useState(initialSystemContext);
    const [userMessage, setUserMessage] = useState(initialUserMessage);
    const [capability, setCapability] = useState(initialCapability);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSubmit({ systemContext, userMessage, capability });
    };

    const renderVariablesGuide = () => {
        switch (templatePurpose) {
            case 0: // LessonGeneration
                return (
                    <>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{Topic}`}</code>{" "}
                            - The specific subject matter.
                        </li>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{Audience}`}</code>{" "}
                            - The target demographic.
                        </li>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{Context}`}</code>{" "}
                            - The Knowledge Base content.
                        </li>
                    </>
                );
            case 1: // Evaluation
                return (
                    <>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{LessonContent}`}</code>{" "}
                            - The final completed lesson text to be evaluated.
                        </li>
                    </>
                );
            case 2: // Critic
                return (
                    <>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{Topic}`}</code>{" "}
                            - The specific subject matter.
                        </li>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{Audience}`}</code>{" "}
                            - The target demographic.
                        </li>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{Context}`}</code>{" "}
                            - The Knowledge Base content.
                        </li>
                        <li>
                            <code className="text-indigo-200 bg-indigo-950/50 px-1.5 py-0.5 rounded font-mono">{`{Draft}`}</code>{" "}
                            - The initial draft generated by the Actor model.
                        </li>
                    </>
                );
            default:
                return null;
        }
    };

    return (
        <Card className="p-6 md:p-8">
            <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                    <Label>Execution Capability *</Label>
                    <select
                        value={capability}
                        onChange={(e) =>
                            setCapability(parseInt(e.target.value, 10))
                        }
                        className="flex h-10 w-full rounded-md border border-zinc-800 bg-zinc-950 px-3 py-2 text-sm text-zinc-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
                    >
                        {Object.entries(CAPABILITY_CONFIG).map(
                            ([value, config]) => (
                                <option key={value} value={Number(value)}>
                                    {config.label}
                                </option>
                            ),
                        )}
                    </select>
                    <Text className="text-xs text-zinc-500 mt-1">
                        {CAPABILITY_CONFIG[capability]?.description}
                    </Text>
                </div>

                <hr className="border-zinc-800 my-8" />

                {/* --- RENDER THE DYNAMIC GUIDE HERE --- */}
                <div className="bg-indigo-950/20 border border-indigo-500/30 rounded-lg p-4 mb-6">
                    <h4 className="text-sm font-semibold text-indigo-300 mb-2 flex items-center gap-2">
                        <svg
                            className="w-4 h-4"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                            />
                        </svg>
                        System Variables Guide
                    </h4>
                    <p className="text-xs text-zinc-300 mb-3">
                        Because this is a{" "}
                        <strong>
                            {PURPOSE_CONFIG[templatePurpose]?.label}
                        </strong>{" "}
                        template, the engine will automatically inject these
                        placeholders:
                    </p>
                    <ul className="text-xs text-zinc-400 space-y-1.5 list-disc list-inside ml-2">
                        {renderVariablesGuide()}
                    </ul>
                </div>

                <div>
                    <Label>System Context *</Label>
                    <Textarea
                        required
                        value={systemContext}
                        onChange={(e) => setSystemContext(e.target.value)}
                        rows={4}
                        className="font-mono text-sm"
                    />
                </div>

                <div>
                    <Label>User Message *</Label>
                    <Textarea
                        required
                        value={userMessage}
                        onChange={(e) => setUserMessage(e.target.value)}
                        rows={8}
                        className="font-mono text-sm"
                    />
                </div>

                <div className="flex justify-end gap-4 pt-6 mt-6 border-t border-zinc-800">
                    <Button
                        type="button"
                        variant="secondary"
                        onClick={onCancel}
                    >
                        Cancel
                    </Button>
                    <Button
                        type="submit"
                        disabled={isSubmitting}
                        className={
                            isSubmitting ? "opacity-50 cursor-not-allowed" : ""
                        }
                    >
                        {isSubmitting ? "Saving..." : "Save New Version"}
                    </Button>
                </div>
            </form>
        </Card>
    );
}
