<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KnowledgeFoundry.Application\KnowledgeFoundry.Application.csproj" />
  </ItemGroup>
</Project>