<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KnowledgeFoundry.Application\KnowledgeFoundry.Application.csproj" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>
</Project>