// <auto-generated />
using System;
using KnowledgeFoundry.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnowledgeFoundry.Infrastructure.Migrations
{
    [DbContext(typeof(KnowledgeFoundryDbContext))]
    [Migration("20260801133207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PromptTemplates", (string)null);
                });

            modelBuilder.Entity("PromptTemplate", b =>
                {
                    b.OwnsOne("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("PromptTemplateId");

                            b1.ToTable("PromptTemplates");

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Identifier");

                            b1.HasKey("PromptTemplateId");

                            b1.ToTable("PromptTemplates");

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.HasKey("PromptTemplateId");

                            b1.ToTable("PromptTemplates");

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Identifier")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
