// <auto-generated />
using System;
using KnowledgeFoundry.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnowledgeFoundry.Infrastructure.Migrations
{
    [DbContext(typeof(KnowledgeFoundryDbContext))]
    [Migration("20260814174055_AddContextPacks")]
    partial class AddContextPacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeFoundry.Domain.ContextPacks.ContextPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ContextPacks", (string)null);
                });

            modelBuilder.Entity("PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PromptTemplates", (string)null);
                });

            modelBuilder.Entity("KnowledgeFoundry.Domain.ContextPacks.ContextPack", b =>
                {
                    b.OwnsMany("KnowledgeFoundry.Domain.ContextPacks.ContextPackVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ActivatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("ArchivedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ContextPackId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("DeprecatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("PublishedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ContextPackId");

                            b1.ToTable("ContextPackVersions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContextPackId");

                            b1.OwnsMany("KnowledgeFoundry.Domain.ContextPacks.ValueObjects.ContextSection", "Sections", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Content")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("ContextPackVersionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ContextPackVersionId");

                                    b2.ToTable("ContextSections", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ContextPackVersionId");
                                });

                            b1.OwnsOne("KnowledgeFoundry.Domain.ContextPacks.ValueObjects.ContextVersionNumber", "VersionNumber", b2 =>
                                {
                                    b2.Property<Guid>("ContextPackVersionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("VersionNumber");

                                    b2.HasKey("ContextPackVersionId");

                                    b2.ToTable("ContextPackVersions");

                                    b2.WithOwner()
                                        .HasForeignKey("ContextPackVersionId");
                                });

                            b1.Navigation("Sections");

                            b1.Navigation("VersionNumber")
                                .IsRequired();
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.ContextPacks.ValueObjects.ContextPackDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("ContextPackId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("ContextPackId");

                            b1.ToTable("ContextPacks");

                            b1.WithOwner()
                                .HasForeignKey("ContextPackId");
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.ContextPacks.ValueObjects.ContextPackIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("ContextPackId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Identifier");

                            b1.HasKey("ContextPackId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ContextPacks");

                            b1.WithOwner()
                                .HasForeignKey("ContextPackId");
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.ContextPacks.ValueObjects.ContextPackName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ContextPackId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.HasKey("ContextPackId");

                            b1.ToTable("ContextPacks");

                            b1.WithOwner()
                                .HasForeignKey("ContextPackId");
                        });

                    b.OwnsMany("KnowledgeFoundry.Domain.ContextPacks.ValueObjects.ContextTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ContextPackId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Value");

                            b1.HasKey("Id");

                            b1.HasIndex("ContextPackId", "Value")
                                .IsUnique();

                            b1.ToTable("ContextTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContextPackId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Identifier")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PromptTemplate", b =>
                {
                    b.OwnsMany("KnowledgeFoundry.Domain.PromptTemplates.PromptTemplateVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ActivatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("ArchivedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Capability")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("DeprecatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("PublishedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PromptTemplateId");

                            b1.ToTable("PromptTemplateVersions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");

                            b1.OwnsMany("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptMessage", "Messages", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Content")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("PromptTemplateVersionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Role")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("PromptTemplateVersionId");

                                    b2.ToTable("PromptMessages", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PromptTemplateVersionId");
                                });

                            b1.OwnsMany("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptVariable", "Variables", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("Name");

                                    b2.Property<Guid>("PromptTemplateVersionId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("PromptTemplateVersionId");

                                    b2.ToTable("PromptVariables", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PromptTemplateVersionId");
                                });

                            b1.OwnsOne("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptVersionNumber", "VersionNumber", b2 =>
                                {
                                    b2.Property<Guid>("PromptTemplateVersionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("VersionNumber");

                                    b2.HasKey("PromptTemplateVersionId");

                                    b2.ToTable("PromptTemplateVersions");

                                    b2.WithOwner()
                                        .HasForeignKey("PromptTemplateVersionId");
                                });

                            b1.Navigation("Messages");

                            b1.Navigation("Variables");

                            b1.Navigation("VersionNumber")
                                .IsRequired();
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("PromptTemplateId");

                            b1.ToTable("PromptTemplates");

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Identifier");

                            b1.HasKey("PromptTemplateId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("PromptTemplates");

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.OwnsOne("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.HasKey("PromptTemplateId");

                            b1.ToTable("PromptTemplates");

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.OwnsMany("KnowledgeFoundry.Domain.PromptTemplates.ValueObjects.PromptTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PromptTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Value");

                            b1.HasKey("Id");

                            b1.HasIndex("PromptTemplateId", "Value")
                                .IsUnique();

                            b1.ToTable("PromptTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PromptTemplateId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Identifier")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
